project:
  type: book
  output-dir: docs

book:
  title: "Quality Improvement With Data"
  author: "Jacob Anhøj"
  date: last-modified
  date-format: iso
  page-footer: "Jacob Anhøj 2023"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 11_chapter1.qmd
    - 21_chapter2.qmd
    - 91_summary.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true



